### ISSUE TITLE
Create Student controller

### ISSUE THREAD

**Issue by chetankudaravalli16** [chetankudaravalli16/mvc-app#1]

**Comment by pranay0987** [comment]
- [ ] creating theStudent model and properties

**Comment by pranay0987** [comment]
- [ ] creating a sample data that fits the Student model

**Comment by pranay0987** [comment]
- [ ] seeding a sample data

**Comment by pranay0987** [comment]
- [ ] routing requests to the controller

**Comment by pranay0987** [comment]
- [ ] implementing your controller (2 json calls, 5 view requests, 3 data actions (create/update/delete)

**Comment by pranay0987** [comment]
- [ ] implementing implementing the five views used to listall/create/read/update/delete (CRUD).

**Comment by pranay0987** [comment]
- [ ] update the application navigation to provide access to the resource

**Comment by pranay0987** [comment]
- [ ] update the application navigation to provide access to the developer page.

**Comment by pranay0987** [comment]
- [ ] Read

**Comment by pranay0987** [comment]
- [ ] Write
