### ISSUE TITLE
Create section controller

### ISSUE THREAD

**Issue by chetankudaravalli16** [chetankudaravalli16/mvc-app#3]

**Comment by pavanreddy4227** [comment]
- [x] creating section model and its properties

**Comment by pavanreddy4227** [comment]
- [x] creating section data that fits the model

**Comment by pavanreddy4227** [comment]
- [ ] seeding your section data

**Comment by pavanreddy4227** [comment]
- [ ] routing requests to your controller

**Comment by pavanreddy4227** [comment]
- [ ] implementing your controller (2 json calls, 5 view requests, 3 data actions (create/update/delete)

**Comment by pavanreddy4227** [comment]
- [ ] implementing the five views used to listall/create/read/update/delete (CRUD)

**Comment by pavanreddy4227** [comment]
- [ ] update the application navigation to provide access to your resource

**Comment by pavanreddy4227** [comment]
- [ ] update the application navigation to provide access to your developer page

**Comment by pavanreddy4227** [comment]
- [ ] Testing

**Comment by pavanreddy4227** [comment]
- [ ] Update
